version: "3.9"

services:
  web:
    build:
      context: /opt/sender25
      dockerfile: Dockerfile
    command: sender25 web-server
    network_mode: host
    volumes:
      - /opt/sender25/config:/config
    restart: unless-stopped

  smtp:
    build:
      context: /opt/sender25
      dockerfile: Dockerfile
    command: sender25 smtp-server
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - /opt/sender25/config:/config
    restart: unless-stopped

  worker:
    build:
      context: /opt/sender25
      dockerfile: Dockerfile
    command: sender25 worker
    network_mode: host
    volumes:
      - /opt/sender25/config:/config
    restart: unless-stopped

  runner:
    profiles: ["tools"]
    build:
      context: /opt/sender25
      dockerfile: Dockerfile
    command: sender25
    network_mode: host
    volumes:
      - /opt/sender25/config:/config
