default: &default
  adapter: mysql2
  reconnect: true
  encoding: "<%= Sender25::Config.main_db.encoding %>"
  pool: <%= Sender25::Config.main_db.pool_size %>
  username: "<%= Sender25::Config.main_db.username %>"
  password: "<%= Sender25::Config.main_db.password %>"
  host: "<%= Sender25::Config.main_db.host %>"
  port: <%= Sender25::Config.main_db.port %>
  database: "<%= Sender25::Config.main_db.database %>"

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
