default: &default
  adapter: mysql2
  reconnect: true
  encoding: "<%= Postal::Config.main_db.encoding %>"
  pool: <%= Postal::Config.main_db.pool_size %>
  username: "<%= Postal::Config.main_db.username %>"
  password: "<%= Postal::Config.main_db.password %>"
  host: "<%= Postal::Config.main_db.host %>"
  port: <%= Postal::Config.main_db.port %>
  database: "<%= Postal::Config.main_db.database %>"

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
