# This is an example Sender25 configuration file for use in 
# test environments. For a production example, see
# the https://github.com/sender25server/install repository.

version: 2

main_db:
  host: 127.0.0.1
  username: root
  password: 
  database: sender25-test

message_db:
  host: 127.0.0.1
  username: root
  password: 
  prefix: sender25-test

logging:
  enabled: false
  rails_log_enabled: false

rails:
  environment: test
  secret_key: 7f27856d26e864bafd49d0df37ad3d1339086e86ef0447e0f1814dde5277452fea97dab9e3aad6dfa11bfe359c82ce302d97bf1e58f6103c4408e4fbad4eeccf
