name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: CI Image Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: andersondeda/postal:ci-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: ci

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: docker-compose pull
        env:
          POSTAL_IMAGE: andersondeda/postal:ci-${{ github.sha }}
      - run: docker-compose run postal sh -c 'bundle exec rspec'
        env:
          POSTAL_IMAGE: andersondeda/postal:ci-${{ github.sha }}
