name: Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: 'The tag to publish'
        required: true
  workflow_call:
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true

jobs:
  publish-image:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            andersondeda/postal:stable
            andersondeda/postal:${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: full
          build-args: |
            VERSION=${{ inputs.tag }}
